name: BIGBOYSMINING
favicon: null
layout_spectrum: 1
typography_spectrum: 0.811678
title: Construction and Maintenance Dredging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b010a'
    - '#ffffff'
    - '#123881'
    - '#d77254'
    - '#bbbda8'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
