analytics: {}
color:
  brandColors:
    - '#0b010a'
    - '#ffffff'
    - '#123881'
    - '#d77254'
    - '#bbbda8'
  brandStrength: 0
  lightness: 0.25
  rhythmicContrast: 0
  saturation: 0.0625
cta: {}
layout_spectrum: 1
name: BIGBOYSMINING
opengraph: {}
purpose: []
typography_spectrum: 0.811678
