analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.668664
  lightness: 0.288492
  rhythmicContrast: 0.171233
  saturation: 0.503425
cta: {}
layout_spectrum: 0.234589
name: BIGBOYSMINING
opengraph: {}
purpose: []
typography_spectrum: 0.296661
