analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.682566
  lightness: 0.479441
  rhythmicContrast: 0.505757
  saturation: 0.503425
cta: {}
layout_spectrum: 0.410362
name: BIGBOYSMINING
opengraph: {}
purpose: []
typography_spectrum: 0.811678
