name: BIGBOYSMINING
favicon: null
layout_spectrum: 0.989309
typography_spectrum: 0.811678
title: Construction and Maintenance Dredging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.347039
  lightness: 0.125
  saturation: 0.60773
  rhythmicContrast: 0
purpose: []
