name: BIGBOYSMINING
favicon: null
layout_spectrum: 0.68743
typography_spectrum: 0.75
title: 'BIGBOYSMINING, Your Dredger, Dredging in New Zealand'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cdd2ce'
    - '#996536'
    - '#192639'
    - '#2a7858'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
