analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.504281
  rhythmicContrast: 0.505757
  saturation: 0.503425
cta: {}
layout_spectrum: 0.989309
name: BIGBOYSMINING
opengraph: {}
purpose: []
typography_spectrum: 0.811678
